# Obtén y conoce tus datos



### 1. Importa las librerías necesarias

In [2]:
import numpy as np
import pandas as pd

### 2. Importa el dataset de este [enlace](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user) y guárdalo en una variable llamada users. Usa pd.read_csv()

In [3]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")
users

,user_id,age,gender,occupation,zip_code
0,1,24,M,technician,85711
1,2,53,F,other,94043
2,3,23,M,writer,32067
3,4,24,M,technician,43537
4,5,33,F,other,15213
...,...,...,...,...,...
938,939,26,F,student,33319
939,940,32,M,administrator,02215
940,941,20,M,student,97229
941,942,48,F,librarian,78209


In [4]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")
users

,user_id,age,gender,occupation,zip_code
0,1,24,M,technician,85711
1,2,53,F,other,94043
2,3,23,M,writer,32067
3,4,24,M,technician,43537
4,5,33,F,other,15213
...,...,...,...,...,...
938,939,26,F,student,33319
939,940,32,M,administrator,02215
940,941,20,M,student,97229
941,942,48,F,librarian,78209


### 3. Muestra las 25 primeros registros


In [5]:
users[0:26:1]

,user_id,age,gender,occupation,zip_code
0,1,24,M,technician,85711
1,2,53,F,other,94043
2,3,23,M,writer,32067
3,4,24,M,technician,43537
4,5,33,F,other,15213
5,6,42,M,executive,98101
6,7,57,M,administrator,91344
7,8,36,M,administrator,05201
8,9,29,M,student,01002
9,10,53,M,lawyer,90703


### 4. Muestra las 25 primeros registros de otra forma

In [6]:
users.head(25)

,user_id,age,gender,occupation,zip_code
0,1,24,M,technician,85711
1,2,53,F,other,94043
2,3,23,M,writer,32067
3,4,24,M,technician,43537
4,5,33,F,other,15213
5,6,42,M,executive,98101
6,7,57,M,administrator,91344
7,8,36,M,administrator,05201
8,9,29,M,student,01002
9,10,53,M,lawyer,90703


### 5. Muestra los últimos 25 registros

In [7]:
users[-1:-26:-1]

,user_id,age,gender,occupation,zip_code
942,943,22,M,student,77841
941,942,48,F,librarian,78209
940,941,20,M,student,97229
939,940,32,M,administrator,02215
938,939,26,F,student,33319
937,938,38,F,technician,55038
936,937,48,M,educator,98072
935,936,24,M,other,32789
934,935,42,M,doctor,66221
933,934,61,M,engineer,22902


In [ ]:
users.tail(25) # otra manera.

,user_id,age,gender,occupation,zip_code
918,919,25,M,other,14216
919,920,30,F,artist,90008
920,921,20,F,student,98801
921,922,29,F,administrator,21114
922,923,21,M,student,E2E3R
923,924,29,M,other,11753
924,925,18,F,salesman,49036
925,926,49,M,entertainment,01701
926,927,23,M,programmer,55428
927,928,21,M,student,55408


### 6. Cuántos registros hay en total en este dataset?
Resuélvelo de al menos dos formas diferentes

In [18]:
registros_total = len(users)
registros_total

943

In [ ]:
total_registros = users.shape[0] # devuelve una tupla y de esa tupla quierp el número de filas (la primera posición del atributo shape).el numero de filas esta en la primera posicion por eso pongo index 0.
print(total_registros)

943


### 7. Cuántas columnas hay en total en este dataset?
Resuélvelo de al menos dos formas diferentes

In [ ]:
total_columns = users.shape[1] # index 1 de la tupla que me devuelve el shape que  hace referencia a la primera columna.
total_columns 

5

In [21]:
total_columns = len(users.columns)
total_columns 

5

### 8. Haz un print de cada uno de los nombres de las columnas

In [22]:
for columna in users.columns:
    print(columna)

user_id
age
gender
occupation
zip_code


### 9. Accede al índice, a los nombres de las columnas y a los valores por separado

In [26]:
print(users.index)
print(users.columns)
print(users.values)

RangeIndex(start=0, stop=943, step=1)
Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='str')
[[1 24 'M' 'technician' '85711']
 [2 53 'F' 'other' '94043']
 [3 23 'M' 'writer' '32067']
 ...
 [941 20 'M' 'student' '97229']
 [942 48 'F' 'librarian' '78209']
 [943 22 'M' 'student' '77841']]


In [12]:
#otra manera
list(users.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [13]:
list(users.columns)

['user_id', 'age', 'gender', 'occupation', 'zip_code']

In [14]:
list(users.values)

[array([1, 24, 'M', 'technician', '85711'], dtype=object),
 array([2, 53, 'F', 'other', '94043'], dtype=object),
 array([3, 23, 'M', 'writer', '32067'], dtype=object),
 array([4, 24, 'M', 'technician', '43537'], dtype=object),
 array([5, 33, 'F', 'other', '15213'], dtype=object),
 array([6, 42, 'M', 'executive', '98101'], dtype=object),
 array([7, 57, 'M', 'administrator', '91344'], dtype=object),
 array([8, 36, 'M', 'administrator', '05201'], dtype=object),
 array([9, 29, 'M', 'student', '01002'], dtype=object),
 array([10, 53, 'M', 'lawyer', '90703'], dtype=object),
 array([11, 39, 'F', 'other', '30329'], dtype=object),
 array([12, 28, 'F', 'other', '06405'], dtype=object),
 array([13, 47, 'M', 'educator', '29206'], dtype=object),
 array([14, 45, 'M', 'scientist', '55106'], dtype=object),
 array([15, 49, 'F', 'educator', '97301'], dtype=object),
 array([16, 21, 'M', 'entertainment', '10309'], dtype=object),
 array([17, 30, 'M', 'programmer', '06355'], dtype=object),
 array([18, 35, '

### 10. Cuál es el tipo de cada columna del dataset?
Hazlo de dos formas diferentes

In [ ]:
print(users.dtypes)

user_id       int64
age           int64
gender          str
occupation      str
zip_code        str
dtype: object


In [16]:
#otra manera
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str  
 3   occupation  943 non-null    str  
 4   zip_code    943 non-null    str  
dtypes: int64(2), str(3)
memory usage: 37.0 KB


In [18]:
#ni idea la otra.

### 11. Haz un print solo de la columna de occupation
Hazlo de dos formas diferentes

In [19]:
users['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

In [20]:
users.occupation

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

### 12. ¿Cuántas profesiones diferentes hay? ¿Y personas por profesión?

In [21]:
users["occupation"].unique()

<StringArray>
[   'technician',         'other',        'writer',     'executive',
 'administrator',       'student',        'lawyer',      'educator',
     'scientist', 'entertainment',    'programmer',     'librarian',
     'homemaker',        'artist',      'engineer',     'marketing',
          'none',    'healthcare',       'retired',      'salesman',
        'doctor']
Length: 21, dtype: str

### 13. ¿Cuál es la profesión más común?

In [ ]:
users["occupation"].mode() 

0    student
Name: occupation, dtype: str

### 14. Obtén un resumen de las principales medidas estadísticas de las variables numéricas.  Usa describe()

In [ ]:
users.describe().T # cuando tengo muchas columnas, el .T me lo traspone.

,count,mean,std,min,25%,50%,75%,max
user_id,943.0,472.000000,272.364951,1.0,236.5,472.0,707.5,943.0
age,943.0,34.051962,12.192740,7.0,25.0,31.0,43.0,73.0


### 15. Obtén un resumen de las principales medidas estadísticas de todas las variables.  Usa describe()

In [ ]:
users.describe(include = "all") #incluir variables no numericas.

,user_id,age,gender,occupation,zip_code
count,943.000000,943.000000,943,943,943
unique,NaN,NaN,2,21,795
top,NaN,NaN,M,student,55414
freq,NaN,NaN,670,196,9
mean,472.000000,34.051962,NaN,NaN,NaN
std,272.364951,12.192740,NaN,NaN,NaN
min,1.000000,7.000000,NaN,NaN,NaN
25%,236.500000,25.000000,NaN,NaN,NaN
50%,472.000000,31.000000,NaN,NaN,NaN
75%,707.500000,43.000000,NaN,NaN,NaN


### 16. Obtén un resumen de las principales medidas estadísticas de solo la columna occupation.  Usa describe()

In [28]:
users.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### 17. ¿Cuál es la edad media?

In [30]:
users.age.mean()
print(users.age.mean())

34.05196182396607


### 18. ¿Cuál es la edad menos frecuente?

In [ ]:
users.age.value_counts().idxmin() #idxmin nos deuelve el indice, osea en que fila esta el valor minimo.

np.int64(7)

In [ ]:
edad = users["age"].value_counts() 
print(edad[edad == edad.min()]) # me devuelve todos los valore sque cuplen esta condicion,

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64
