![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [25]:
my_array = np.arange(0 , 10, 1) # con arange le pongo (start, stop, step)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
print(my_array[-1:0:-2]) # le pongo entre corchetes (start: -1 ppara que empiece desde el último;stop: 0 para que incluya el 1, y step: -2 para ir hacia atrás de dos en dos.

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array[-2:-4:-1]) # imprime los elementos 8 y 7 recorriendo el array hacia atrás

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
print(my_array[2::-1]) # imprime desde el segundo al primer hacia atras.

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
my_matrix = np.arange(1, 21).reshape(4,5)
print(my_matrix)

print(np.flip(my_matrix))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
#imprimo las dos primras filas, y dos primeras columnas.
print(my_matrix) #printeo la original para ver luego el cambio.
print("2 primeras filas y 2 primeras columnas\n", my_matrix[:2, :2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2 primeras filas y 2 primeras columnas
 [[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
print(my_matrix) 
print("primera y tercera fila con saltos de 2 \n", my_matrix[0:3:2, 0::2]) #filas(0,3 con saltos de 2) y columnas(0 hasta el final con saltos de 2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
primera y tercera fila con saltos de 2 
 [[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
print(my_matrix)
# de las primeras 3 filas, invertir el orden de las columnas.

print("primera y tercera fila con saltos de 2 \n", my_matrix[0:3, -1::-1])
 
# slicing no me cambia la matriz original, solo me lo muestra de otra manera. por eso no he hecho el copy a la amtriz original.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
primera y tercera fila con saltos de 2 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perrro", "Gato", "Loro", "Perro"])
#primera opcion que se me ocurre es imprimir por posicion.
print(x[0::3])

#la otra opcion que creo que es la mas correcta es filtrar por valor.
print(x[x == "Loro"]) # de esta manera me devuelve todos los elementos que tiene la palabra "loro"

['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [63]:
secuencia = np.arange(20)
print(secuencia)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [65]:
#transformo la secuencia en un array de 2 matrices de 5x2
print(secuencia.reshape(2,5,2))


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
array_10 = np.zeros(10, dtype = int) # pongo dtype int para que no me salga los numeros (0) en float.
print(array_10)
print("Memoria ocupada: ", array_10.nbytes, "bytes")

#sustituimos el 4to elemento por 1.
array_10[3] = 1
print(array_10)

[0 0 0 0 0 0 0 0 0 0]
Memoria ocupada:  80 bytes
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
V = np.arange(start =10, stop=50, step=1)
print(V)

V_invertido = V[-1::-1]
print(V_invertido)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [24]:
vector = np.array([1, 2, 0, 0, 4, 0])

#encontrar indices  de los valores que no sean 0.

indices = np.nonzero(vector)[0] # np.nonzero() devuelve una tupla.
print(indices)


[0 1 4]


In [25]:
# encapsular en funcion.

def indices_nonzero(vector):
    return np.nonzero(vector)[0]

In [26]:
# si Probamos la funcion:
print(indices_nonzero(vector))

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [43]:
matriz_10x10 = np.random.randint(0, 10,(10,10))
print(matriz_10x10)

print("máximo: ", matriz_10x10.max())

print("mínimo: ", matriz_10x10.min())

[[8 5 1 9 5 3 1 6 3 4]
 [3 2 3 4 7 0 6 7 5 4]
 [9 0 8 6 7 5 0 7 9 7]
 [0 5 6 8 3 0 8 1 6 9]
 [6 2 6 4 2 2 3 2 8 0]
 [8 4 8 6 9 4 0 0 7 9]
 [4 1 6 6 4 8 7 1 3 2]
 [6 8 7 9 3 2 5 5 9 2]
 [0 9 8 0 2 6 7 0 2 7]
 [6 8 2 2 4 9 0 4 7 3]]
máximo:  9
mínimo:  0


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vector_30 = np.random.random(30)
print(vector_30)

#media de los elementos.
print("media: ", vector_30.mean())

[0.92494241 0.72176403 0.0341143  0.52979102 0.49975585 0.05273167
 0.09886025 0.06606943 0.73017933 0.90292881 0.53777895 0.19789694
 0.05965578 0.1562863  0.81680367 0.34974027 0.66451125 0.62313706
 0.51008965 0.30129241 0.2880902  0.72926158 0.57108924 0.19594871
 0.27370619 0.69767736 0.03359397 0.77460591 0.75037688 0.70620424]
media:  0.4599627889398791


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [65]:
#creamos la matriz (6x6):
array_2D = np.zeros((6,6))
# print(array_2D)

#cambiar los bordes a 1s:
array_2D[0,:]= 1 # primera fila
# print(array_2D)

array_2D[-1,:]= 1 #ultima fila
# print(array_2D)

array_2D[:,0]= 1 # primera columna
# print(array_2D)

array_2D[:,-1]= 1 # última columna


print(array_2D)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#otra manera de hacerlo. opción recomendable.
n = np.ones((6, 6), dtype = int)
n[1:-1, 1:-1] = 0
print(n)


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [16]:
#creamos la matriz (8x8):
array_8x8 = np.zeros((8,8), dtype = int)

array_8x8[0::2, 1::2] = 1 #pone 1 en filas pares y columnas impares
# print(array_8x8)

array_8x8[1::2, ::2] = 1 #pone 1 en filas impares y columnas pares

print(array_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
matriz_tile = np.tile([[0,1],[1,0]], [4,4]) # es duplicar vector por los numeros que tu quieras.
print(matriz_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [86]:
matriz_5x5 =np.random.random((5, 5))
print("Matriz original: ", matriz_5x5)

media_matriz_5x5 = matriz_5x5.mean()
print("Media: ", media_matriz_5x5)

desv_matriz_5x5 = matriz_5x5.std()
print("Desviacion estandar:", desv_matriz_5x5)

matriz_5x5_norm = (matriz_5x5 - media_matriz_5x5) / desv_matriz_5x5

print("Matriz normalizada: ", matriz_5x5_norm)

Matriz original:  [[0.68971421 0.7192901  0.24773223 0.10097002 0.4731673 ]
 [0.80382361 0.0545692  0.25903735 0.11019843 0.36520964]
 [0.36452829 0.74666332 0.98846616 0.05870381 0.457375  ]
 [0.96791804 0.06173774 0.33318192 0.39462693 0.87564996]
 [0.1764174  0.68793416 0.25480529 0.67355732 0.48920789]]
Media:  0.45417941197818124
Desviacion estandar: 0.2905080413785358
Matriz normalizada:  [[ 0.81076859  0.91257608 -0.7106419  -1.21583346  0.06536098]
 [ 1.20356115 -1.37555647 -0.6717269  -1.18406698 -0.30625581]
 [-0.30860118  1.00680141  1.83914615 -1.3613241   0.011     ]
 [ 1.76841449 -1.35088057 -0.41650309 -0.20499426  1.4508051 ]
 [-0.95612505  0.80464125 -0.68629468  0.75515261  0.12057662]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
secuencia_num = np.arange(0, 11)
print(secuencia_num)

new_Secuence = secuencia_num.copy()
new_Secuence[(new_Secuence >= 3) & (new_Secuence <= 8)]= -1
print(new_Secuence)
# otra manera:
# array_19=np.where((secuencia_num > 3) & (secuencia_num < 8), -1, secuencia_num)
# print(array_19)
neg_secuence = secuencia_num.copy()
neg_secuence[(neg_secuence >= 3) & (neg_secuence <= 8)] *= -1
print(neg_secuence)
# otra manera:
# array_19=np.where((secuencia_num > 3) & (secuencia_num < 8),-secuencia_num, secuencia_num)
# print(array_19)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
